#!/usr/bin/env python3
"""Dependency-light documentation audit for Model Generator."""

from __future__ import annotations

import argparse
import dataclasses
import datetime as _dt
import re
import sys
from pathlib import Path
from typing import Iterable


VALID_DOC_STATUS = {
    "proposed",
    "living",
    "stable",
    "frozen",
    "historical",
    "append-only",
    "generated",
}
VALID_ADR_STATUS = {"accepted", "proposed", "superseded", "rejected"}
VALID_TIERS = {"meta", "platform", "tool", "workflow", "decision", "record"}

REQUIRED_PATHS = [
    "README.md",
    "AGENTS.md",
    "CLAUDE.md",
    "docs/PROJECT_VISION.md",
    "docs/OPERATING_MODEL.md",
    "docs/UX_VISION.md",
    "docs/ARCHITECTURE.md",
    "docs/TOOL_SPEC.md",
    "docs/DOC_SPEC.md",
    "docs/AUDIT.md",
    "docs/ONBOARDING.md",
    "docs/NEXT.md",
    "docs/HISTORY.md",
    "docs/INBOX.md",
    "docs/TECH_DEBT.md",
    "docs/REFERENCES.md",
    "docs/MAP.md",
    "docs/audit-log.md",
    "docs/workflows/BOARD_MOUNT_DESIGNER.md",
    "docs/workflows/BOARD_MOUNT_ASSEMBLY.md",
    "docs/decisions/README.md",
    "docs/freezes/README.md",
    "tools/doc-audit/README.md",
    "tools/doc-audit/doc_audit.py",
]

FRONTMATTER_REQUIRED_UNDER = ("docs/",)


@dataclasses.dataclass
class Finding:
    severity: str
    path: str
    message: str

    def line(self) -> str:
        return f"{self.severity}: {self.path}: {self.message}"


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def parse_frontmatter(text: str) -> tuple[dict[str, object], str]:
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}, text
    raw = text[4:end].splitlines()
    body = text[end + 5 :]
    data: dict[str, object] = {}
    current_key: str | None = None
    for line in raw:
        if not line.strip():
            continue
        if line.startswith("  - ") and current_key:
            value = line[4:].strip()
            data.setdefault(current_key, [])
            if isinstance(data[current_key], list):
                data[current_key].append(value)
            continue
        if ":" in line:
            key, value = line.split(":", 1)
            key = key.strip()
            value = value.strip()
            current_key = key
            if value == "":
                data[key] = []
            else:
                data[key] = value.strip('"')
    return data, body


def is_date(value: object) -> bool:
    if not isinstance(value, str):
        return False
    try:
        _dt.date.fromisoformat(value)
        return True
    except ValueError:
        return False


def markdown_files(root: Path) -> list[Path]:
    ignored = {".git"}
    files = []
    for path in root.rglob("*.md"):
        if any(part in ignored for part in path.parts):
            continue
        files.append(path)
    return sorted(files)


def docs_for_map(root: Path) -> list[tuple[str, dict[str, object]]]:
    docs: list[tuple[str, dict[str, object]]] = []
    for path in markdown_files(root):
        r = rel(path, root)
        if not r.startswith("docs/"):
            continue
        if r == "docs/MAP.md":
            continue
        meta, _ = parse_frontmatter(path.read_text(encoding="utf-8"))
        if meta:
            docs.append((r, meta))
    return docs


def generate_map(root: Path, updated: str | None = None) -> str:
    map_updated = updated or _dt.date.today().isoformat()
    grouped: dict[str, list[tuple[str, dict[str, object]]]] = {}
    for path, meta in docs_for_map(root):
        grouped.setdefault(str(meta.get("tier", "meta")), []).append((path, meta))

    lines = [
        "---",
        "title: Documentation Map",
        "tier: meta",
        "status: generated",
        f"updated: {map_updated}",
        "related:",
        "  - docs/DOC_SPEC.md",
        "---",
        "",
        "# Documentation Map",
        "",
        "<!-- BEGIN GENERATED MAP -->",
        "",
        "Generated by `python3 tools/doc-audit/doc_audit.py --write-map`.",
        "",
    ]
    tier_order = ["meta", "platform", "workflow", "tool", "decision", "record"]
    for tier in tier_order:
        entries = sorted(grouped.get(tier, []), key=lambda item: item[0])
        if not entries:
            continue
        lines.append(f"## {tier.title()}")
        lines.append("")
        for path, meta in entries:
            status = meta.get("status", "unknown")
            title = meta.get("title", path)
            link = path[5:] if path.startswith("docs/") else path
            lines.append(f"- [{title}]({link}) - `{status}`")
        lines.append("")
    lines.extend(["<!-- END GENERATED MAP -->", ""])
    return "\n".join(lines)


def local_link_target(path: Path, link: str) -> Path | None:
    if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", link):
        return None
    if link.startswith("#"):
        return None
    target = link.split("#", 1)[0]
    if not target:
        return None
    if target.startswith("/"):
        return None
    return (path.parent / target).resolve()


def audit(root: Path, required_paths: Iterable[str] = REQUIRED_PATHS) -> list[Finding]:
    findings: list[Finding] = []
    root = root.resolve()

    for required in required_paths:
        if not (root / required).exists():
            findings.append(Finding("ERROR", required, "required path is missing"))

    all_md = markdown_files(root)
    doc_paths = {rel(path, root): path for path in all_md}

    for r, path in doc_paths.items():
        text = path.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(text)
        if r.startswith(FRONTMATTER_REQUIRED_UNDER):
            if not meta:
                findings.append(Finding("ERROR", r, "missing YAML frontmatter"))
            else:
                for key in ("title", "tier", "status", "updated"):
                    if key not in meta:
                        findings.append(Finding("ERROR", r, f"missing frontmatter field `{key}`"))
                tier = meta.get("tier")
                status = meta.get("status")
                if tier and tier not in VALID_TIERS:
                    findings.append(Finding("ERROR", r, f"invalid tier `{tier}`"))
                if status and r.startswith("docs/decisions/") and r != "docs/decisions/README.md":
                    if status not in VALID_ADR_STATUS:
                        findings.append(Finding("ERROR", r, f"invalid ADR status `{status}`"))
                elif status and status not in VALID_DOC_STATUS:
                    findings.append(Finding("ERROR", r, f"invalid status `{status}`"))
                if "updated" in meta and not is_date(meta["updated"]):
                    findings.append(Finding("ERROR", r, "`updated` must be YYYY-MM-DD"))
                if "audited" in meta and not is_date(meta["audited"]):
                    findings.append(Finding("ERROR", r, "`audited` must be YYYY-MM-DD"))
                related = meta.get("related", [])
                if related and not isinstance(related, list):
                    findings.append(Finding("ERROR", r, "`related` must be a list"))
                for item in related if isinstance(related, list) else []:
                    if not (root / item).exists():
                        findings.append(Finding("ERROR", r, f"related path does not exist: {item}"))

        for match in re.finditer(r"\[[^\]]+\]\(([^)]+)\)", text):
            target = local_link_target(path, match.group(1))
            if target and not target.exists():
                findings.append(Finding("ERROR", r, f"broken local markdown link: {match.group(1)}"))

        headings = re.findall(r"^(#{1,6})\s+(.+)$", body, flags=re.MULTILINE)
        seen: set[str] = set()
        for _, heading in headings:
            normalized = heading.strip().lower()
            if normalized in seen:
                findings.append(Finding("WARN", r, f"duplicate heading `{heading}`"))
            seen.add(normalized)

    next_path = root / "docs/NEXT.md"
    if next_path.exists() and "## START HERE" not in next_path.read_text(encoding="utf-8"):
        findings.append(Finding("ERROR", "docs/NEXT.md", "missing literal `## START HERE` resume anchor"))

    claude = root / "CLAUDE.md"
    if claude.exists():
        text = claude.read_text(encoding="utf-8")
        if "AGENTS.md" not in text or len(text.splitlines()) > 8:
            findings.append(Finding("ERROR", "CLAUDE.md", "must remain a thin pointer to AGENTS.md"))

    adr_dir = root / "docs/decisions"
    if adr_dir.exists():
        numbers: dict[str, str] = {}
        adr_files = sorted(p for p in adr_dir.glob("[0-9][0-9][0-9][0-9]-*.md"))
        for adr in adr_files:
            number = adr.name[:4]
            r = rel(adr, root)
            if number in numbers:
                findings.append(Finding("ERROR", r, f"duplicate ADR number also used by {numbers[number]}"))
            numbers[number] = r
            meta, _ = parse_frontmatter(adr.read_text(encoding="utf-8"))
            if meta.get("adr") != number:
                findings.append(Finding("ERROR", r, f"frontmatter adr must be {number}"))
            if meta.get("status") not in VALID_ADR_STATUS:
                findings.append(Finding("ERROR", r, "ADR status must be accepted/proposed/superseded/rejected"))
            if not is_date(meta.get("date")):
                findings.append(Finding("ERROR", r, "ADR date must be YYYY-MM-DD"))
        index = adr_dir / "README.md"
        if index.exists():
            index_text = index.read_text(encoding="utf-8")
            for adr in adr_files:
                if adr.name not in index_text:
                    findings.append(Finding("ERROR", "docs/decisions/README.md", f"missing ADR link for {adr.name}"))

    debt = root / "docs/TECH_DEBT.md"
    if debt.exists():
        ids = re.findall(r"\bTD-\d{4}\b", debt.read_text(encoding="utf-8"))
        for debt_id in sorted(set(x for x in ids if ids.count(x) > 1)):
            findings.append(Finding("ERROR", "docs/TECH_DEBT.md", f"duplicate tech debt id {debt_id}"))

    inbox = root / "docs/INBOX.md"
    if inbox.exists():
        text = inbox.read_text(encoding="utf-8")
        for match in re.finditer(r"^###\s+(CAP-[^\n]+)(.*?)(?=^###\s+|\Z)", text, flags=re.MULTILINE | re.DOTALL):
            block = match.group(2)
            if "Status:" not in block:
                findings.append(Finding("ERROR", "docs/INBOX.md", f"{match.group(1)} missing status"))
            if "deferred" in block.lower() and "recall" not in block.lower():
                findings.append(Finding("ERROR", "docs/INBOX.md", f"{match.group(1)} deferred without recall hook"))

    map_path = root / "docs/MAP.md"
    if map_path.exists():
        actual = map_path.read_text(encoding="utf-8")
        actual_meta, _ = parse_frontmatter(actual)
        current_updated = actual_meta.get("updated")
        expected = generate_map(root, str(current_updated) if is_date(current_updated) else None)
        if actual != expected:
            findings.append(Finding("ERROR", "docs/MAP.md", "generated map is out of date"))

    if (root / "src").exists():
        findings.append(Finding("INFO", "src", "product code exists; run judgement lenses for code/document alignment"))

    return findings


def write_map(root: Path) -> None:
    map_path = root / "docs/MAP.md"
    map_path.write_text(generate_map(root), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="repository root")
    parser.add_argument("--write-map", action="store_true", help="regenerate docs/MAP.md")
    parser.add_argument("--check", action="store_true", help="run the documentation audit")
    args = parser.parse_args(argv)

    root = Path(args.root)
    if args.write_map:
        write_map(root)
    if args.check or not args.write_map:
        findings = audit(root)
        for finding in findings:
            print(finding.line())
        errors = [f for f in findings if f.severity == "ERROR"]
        if errors:
            print(f"doc-audit: FAIL ({len(errors)} error(s), {len(findings)} finding(s))")
            return 1
        print(f"doc-audit: PASS ({len(findings)} non-blocking finding(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
